### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2016#1]
Brian says:

> PTT would like to put back the wishlist - I think we can use the same box we had last year (unless it has a year on it...)

Unfortunately it does. Here is what it looks like:
![wishlist](http://torontojazz.com/sites/default/files/field/image/wishlist-2015.png)

**Comment by andrewfn** [comment]
Hi @brianblain
As soon as you have an updated banner, let me know and I'll put it online.

**Comment by brianblain** [comment]
Waiting on Dragan. B

**Comment by brianblain** [comment]
OK - Dragan has updated the art. Please proceed

**Comment by andrewfn** [comment]
Great, I'm on to it now.

**Comment by andrewfn** [comment]
The wishlist is now active and I have put in Dragan's new banner at the top of the site. 
Thanks Dragan @mplmnt
