### ISSUE TITLE
Adding "presented by" info to shows

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2016#15]
@brianblain says: I have to add some "presented by" info to some of the shows.  Can I do that once on the "Club Series" or do I need to do it on each individual show.

**Comment by andrewfn** [comment]
I can add a "special series" for you if there are a lot of concerts, otherwise you will have add it individually to each one.

**Comment by brianblain** [comment]
that's OK - i did them separately

**Comment by andrewfn** [comment]
ok.

**Comment by brianblain** [comment]
never got word of "go live" launch time but I see Anna is tweeting that it will be Tuesday Morning so unless you hear otherwise, do it first thing Tues
