### ISSUE TITLE
Double Bill Pic

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#17]
how can we best display pic of both in the calendar?

Lee Fields & The Expressions / Allen Stone Double bill

![lfields-jstone](https://cloud.githubusercontent.com/assets/11864078/14619264/9ff8fad2-0584-11e6-8d9f-36e7c2eea360.jpg)

**Comment by brianblain** [comment]
the other double bill:  

Joey Alexander Trio / Ramsey Lewis Quartet

![rlewis-jalexander](https://cloud.githubusercontent.com/assets/11864078/14619676/877487ae-0586-11e6-91a4-29255eff597a.jpg)

**Comment by andrewfn** [comment]
I'm experimenting with the best way to do this.

**Comment by mplmnt** [comment]
Just clicked on this by chance. We have had something like this before http://archive2013.jazz.to/?_ga=1.261281357.1111064814.1457316177 
and I do remember others just can't find them in the archives anymore.

hope that helps

**Comment by brianblain** [comment]
that's the solution!

**Comment by andrewfn** [comment]
Yes, this is actually what I was going to suggest as an easy way to get the effect.
- Great a new artist called: **Lee Fields & The Expressions / Allen Stone**
- Add the new picture to this "artist"
- In the artist description should simply be: **Double bill**
- Add this "artist" to the concert and make them first on the list so the double pic will show.

At some point I'll figure out a way to make it look cleaner on the concert page
