### ISSUE TITLE
2016 submission box

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#2]
can you make it active now. Link to torontojazz.com/artist-submissions.Thanks, B

**Comment by andrewfn** [comment]
The submissions form looks like it is working successfully.
- You have it currently linked to the Festival menu.

Last year you had an ad for it as well. The ad is still linked to the form, but not currently active. It can be controlled here:
http://torontojazz.com/node/4422/edit?destination=admin/content/simpleads
However, the year should be changed to 2016 on the image before the ad is made active.
What would you like me to do?

**Comment by brianblain** [comment]
here is the 2016 version of the submissions ad.  Link to same page as the
submissions menu item. Thanks, B

On Thu, Nov 5, 2015 at 11:55 PM, Andrew Fountain notifications@github.com
wrote:

> The submissions form looks like it is working successfully.
> - You have it currently linked to the Festival menu.
> 
> Last year you had an ad for it as well. The ad is still linked to the
> form, but not currently active. It can be controlled here:
> http://torontojazz.com/node/4422/edit?destination=admin/content/simpleads
> However, the year should be changed to 2016 on the image before the ad is
> made active.
> What would you like me to do?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2016/issues/2#issuecomment-154285654.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
With github you can just drag the image and drop it into your reply on the github page. But not from email.
It's active now!
