### ISSUE TITLE
Ticket links on home page

### ISSUE THREAD

**Issue by mplmnt** [jazzto/2016#22]
Howard has requested that we include ticket links with each concert on the home page to make buying as easy as possible.
This should simply say "BUY TICKETS"  to stand out from the other information and would link to corresponding concert ticket link.

**Comment by andrewfn** [comment]
We can probably do that. Once things have settled down with today's launch I'll refresh the dev site and we can try it out.

**Comment by mplmnt** [comment]
As you can imagine he sees this an important sales tool so the sooner the better.
Thank you.

**Comment by andrewfn** [comment]
Take a look at this http://test.torontojazz.com/
@plousia will need to theme the link

**Comment by mplmnt** [comment]
Exactly that. 
Lets do it in gold so it stands out and have it be in line with the other text and that should be good,

thank you!

**Comment by plousia** [comment]
OK, should be done. Please take a look at test.torontojazz.com and confirm.

**Comment by mplmnt** [comment]
Looks good to go. Thanks!

**Comment by andrewfn** [comment]
Change is now live.

**Comment by andrewfn** [comment]
Just refreshed the cache which might have caused a delay in the new css getting through on the production site.

**Comment by mplmnt** [comment]
Just checked on a three different machines,  flushed cashes. Checked on ie, firefox, chrome, and safari still the css is not coming through.

**Comment by andrewfn** [comment]
Was away for a bit and just checking again. Is the problem still there?
Hopefully by now the change will have worked through all the layers of cache.

**Comment by mplmnt** [comment]
Looks good now on all of my browsers.
thank you
