### ISSUE TITLE
Changing Donate box in the header to Tickets and Passes

### ISSUE THREAD

**Issue by mplmnt** [jazzto/2016#23]
Can we please change the donate box in the header to the ticket box.
Andrew I will email this to you as well just in case.
![tickets](https://cloud.githubusercontent.com/assets/11934556/14641740/bb31a31c-0615-11e6-9c95-31f25333f6d0.png)

**Comment by andrewfn** [comment]
In previous years we rotate the banner in the top right corner between
- tickets
- passes
- donate

I've set it up to be your new banner rotating with donate. It draws more attention to it having it changing.
If you didn't want the donate banner you could have two banners for tickets and passes to get more attention.

**Comment by mplmnt** [comment]
Since we are on sale now can we just have static one.
If he requests donate to be back there we can. It is all about sales sales sales now.

thanks

**Comment by andrewfn** [comment]
What I was trying to say is that if you want to drive sales, you will get a lot more attention with a rotating box, even if they both have the tickets landing page.
I'll take out the rotation for now.
