### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#25]
not sure how this got left last year but do we need to do something to track/report on clicks for sponsors - and as I recall, one sponsor even wanted stats on how many people clicked on the shows they were sponsoring...

**Comment by andrewfn** [comment]
- The ad module that we use tracks all views and clicks of the banner ads that appear on the right (both large and small banners).
- I would have to know specifically in advance if there is anything else you want to track.

**Comment by brianblain** [comment]
I'll get more detail from Aileen on that.  Pretty smooth switchover today.  Thanks to you and Susana.

**Comment by andrewfn** [comment]
<h1>Jazz Stats for 2016 season (Aug 2015—July 2016)</h1>

<h2 style="color: darkblue;">Overal Stats for <a target="_blank" href="http://torontojazz.com">torontojazz.com</a></h2>

<table class="borders headtop" style="border-width: 2px; border-spacing:2px; border-style: outset; border-color: gray;"><thead>
<tr>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;"></th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2016 </th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2015 </th></tr>
</thead><tbody>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total pageviews for website </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">960,587 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">1,094,175 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total number of Visitors </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">267,172 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">297,688 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total number of Unique Visitors </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">185,575 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">207,463 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Avg. Visitor Duration on website (min:sec) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:45 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:49 </td></tr>
</tbody></table>

<h2 style="color: darkblue;">TD Ad  Stats</h2>

<table class="borders headtop" style="border-width: 2px; border-spacing:2px; border-style: outset; border-color: gray;"><thead>
<tr>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;"></th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2016 </th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2015 </th></tr>
</thead><tbody>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total impressions of TD branded logo on top banner </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">960,587 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">1,094,175 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total  Visitors while TD ad was on website (ad impressions) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">55,548 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">54,099 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Unique Visitors while TD ad was on website </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">19,534 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">26,738 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Visitor Duration while TD ad was on website (Approx) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:45 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">02:49 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">TD banner Click-Throughs </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">105 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">75 </td></tr>
</tbody></table>

**Comment by andrewfn** [comment]
<h1>Jazz Stats for 2016 season (Aug 2015—July 2016)</h1>

<h2 style="color: darkblue;">Overal Stats for <a target="_blank" href="http://torontojazz.com">torontojazz.com</a></h2>

<table class="borders headtop" style="border-width: 2px; border-spacing:2px; border-style: outset; border-color: gray;"><thead>
<tr>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;"></th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2016 </th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2015 </th></tr>
</thead><tbody>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total pageviews for website </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">960,587 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">1,094,175 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total number of Visitors </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">267,172 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">297,688 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total number of Unique Visitors </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">185,575 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">207,463 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Avg. Visitor Duration on website (min:sec) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:45 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:49 </td></tr>
</tbody></table>

<h2 style="color: darkblue;">TD Ad  Stats</h2>

<table class="borders headtop" style="border-width: 2px; border-spacing:2px; border-style: outset; border-color: gray;"><thead>
<tr>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;"></th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2016 </th>
<th style="border-width:1px; padding: 3px; border-style:inset; background-color:#DDD; text-align:left; vertical-align:top;">2015 </th></tr>
</thead><tbody>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total impressions of TD branded logo on top banner </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">960,587 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">1,094,175 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Total  Visitors while TD ad was on website (ad impressions) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">55,548 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">54,099 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Unique Visitors while TD ad was on website </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">19,534 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">26,738 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">Visitor Duration while TD ad was on website (Approx) </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">2:45 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">02:49 </td></tr>
<tr>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">TD banner Click-Throughs </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">105 </td>
<td style="border-width:1px; padding: 3px; border-style:inset; vertical-align:top;">75 </td></tr>
</tbody></table>

**Comment by brianblain** [comment]
I think one stat TD would like is the number of impressions/visitors on
pages where their logo/ad appears. B

On Tue, Apr 19, 2016 at 3:37 PM, Andrew Fountain notifications@github.com
wrote:

> - The ad module that we use tracks all views and clicks of the banner
>   ads that appear on the right (both large and small banners).
> - I would have to know specifically in advance if there is anything
>   else you want to track.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2016/issues/25#issuecomment-212084314

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival  June 23 - July 3, 2016
30th Anniversary

**Comment by andrewfn** [comment]
The first line on the TD chart is:
**Total impressions of TD branded logo on top banner**
I think that's what you were asking for: "the number of impressions on pages where their logo appears"

The number of unique visitors who would see their banner would be 267,172 (since you can't visit the site without seeing it).
Is that the information you were looking for or did I misunderstand?
