### ISSUE TITLE
printable Schedule - urgent

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#26]
we still have last year's!

**Comment by brianblain** [comment]
maybe disable/hide the link until we have it ready...

**Comment by andrewfn** [comment]
It's the old caching problem.
I spend much of the morning getting it right, but didn't clear the cache afterwards.
Just done it, so please check again.

**Comment by brianblain** [comment]
yes good.  I had just made Opera House sticky to top section (and there's been more changes) Do you need to manually refresh?

**Comment by andrewfn** [comment]
The printable schedule is tricky because the page breaks have to be put in manually so that it looks good. I'll re-create it again this evening and not forget to refresh the cache.
The online schedule does not need the cache cleared.
