### ISSUE TITLE
clearing out comments from last year

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#27]
I just came across some facebook comments on a venue page.  Maybe there's more. How do we delete them

http://torontojazz.com/venue/outdoor-stage-nathan-phillips-square

**Comment by andrewfn** [comment]
Just doing some research and I don't see an easy way.
The facebook block is actually generated by fb and we display it in an iframe. If it really bothered us, we could maybe block comments from that particular page.
What you are supposed to do is this: you can set it to display the most recent (say 10) comments, and older comments will simply get pushed off.
