### ISSUE TITLE
remove Howard Kerbel from contact us page feedback form

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#28]

**Comment by andrewfn** [comment]
Done

**Comment by brianblain** [comment]
thank you.  Is there a show you would like to attend in the big tent this
year?

On Thu, Jun 16, 2016 at 2:52 PM, Andrew Fountain notifications@github.com
wrote:

> Done
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jazzto/2016/issues/28#issuecomment-226578880, or mute
> the thread
> https://github.com/notifications/unsubscribe/ALUIDoJ3b39RGV1apWEFuWjobNayOLNEks5qMZtjgaJpZM4I3hkd
> .

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival  June 23 - July 3, 2016
30th Anniversary
