### ISSUE TITLE
Concert duplication on home page

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2016#29]
Concert listings are being duplicated on the home page - right now the Fields/Stone concert is listed three times, and Gregory Porter twice.  Please fix asap.

**Comment by andrewfn** [comment]
Ok. I'm on to it

**Comment by brianblain** [comment]
Yikes!

**Comment by andrewfn** [comment]
Fixed it.
There was a security update for the underlying Drupal technology that has just become active. Unfortunately the fix introduced a bug (which is what we were seeing). I have reverted the update and will re-apply it when they have corrected the problem.

**Comment by joshgrossman** [comment]
Thanks!

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27
