### ISSUE TITLE
home page changes at end of festival

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2016#30]
@brianblain writes:
can you do this without too much trouble?  
- Remove 6 of the 12 boxes and have a big text header saying "FINAL WEEKEND"
- then on Sun/Mon we'll have to change again - not exactly sure to what but probably our year-round look

**Comment by andrewfn** [comment]
Yes, I can do that now.
In previous years we have ended the festival with a photo on the front page

**Comment by brianblain** [comment]
great - asap, B

On Fri, Jul 1, 2016 at 1:49 PM, Andrew Fountain notifications@github.com
wrote:

> Yes, I can do that now.
> In previous years we have ended the festival with a photo on the front page
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jazzto/2016/issues/30#issuecomment-230008468, or mute
> the thread
> https://github.com/notifications/unsubscribe/ALUIDs57cN2bkKRuJIxaoPyF4fEazl-Gks5qRVM0gaJpZM4JDWWn
> .

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival  June 23 - July 3, 2016
30th Anniversary

**Comment by andrewfn** [comment]
Down to 6 boxes. now.
Working on "Final Weekend"

**Comment by andrewfn** [comment]
How does that look?

**Comment by andrewfn** [comment]
Change now applied to mobile site as well.

**Comment by brianblain** [comment]
I'm out so can only see mobile. Make "final weekend" as big and bold as can fit. Thanks, b

**Comment by andrewfn** [comment]
Now its

# BIG AND BOLD

And i'm currently running the annual archive of the festival site

**Comment by brianblain** [comment]
I guess they'll be wanting stats. Nobody's asked yet. B
