### ISSUE TITLE
add text to contact page

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2016#31]
Could you please add the following text to the top of the contact page (http://torontojazz.com/contact):

---

<b>If you are an artist looking to make a submission to the TD Toronto Jazz Festival, please visit our <a href="http://torontojazz.com/artist-submissions">artist submission page</a>.</b>

---

Thanks.

Josh

**Comment by andrewfn** [comment]
Added.
Have a look at let me know if there are any problems.
(Note that any links within the site should not contain the http://torontojazz.com but just start with /
otherwise people using a mobile device will be forced into the desktop site.)

**Comment by joshgrossman** [comment]
All good - thanks.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27
