### ISSUE TITLE
archive old ad's guide posts?

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2016#33]
Hi Andrew,

I'd like to get back to the Artistic Director's Guide to Jazz.  On http://torontojazz.com/guide, is it possible to hide old posts?  I'd like to avoid confusion where if someone sees an old post they might think that artist is coming again this year.

I don't want to delete the old posts - if an artist is returning I'll simply update the older post - but just hide them.

Josh

**Comment by andrewfn** [comment]
The easiest way to do this is to unpublish the post, which simple makes it invisible to the web.
You can do this by selecting **Publishing options** from the very bottom of the page and unchecking the Published checkbox.
There are a lot of old posts, (around 70). Do you want them all hidden? If so, it would probably be better for me to write a script to do that.
Once you have your first new guide post written, let me know and I'll re-enable the box on the front page.

**Comment by joshgrossman** [comment]
Thanks Andrew.  Yes please - let's unpublish all of them.  And once unpublished, they'll still be searchable from the http://torontojazz.com/admin/content page?

**Comment by andrewfn** [comment]
All unpublished.
Yes, you can still find them all from content, and you can limit the list to the content type of Directors Guide which will only show your posts.
b.t.w. this is the 2016 issue queue. Can you put new stuff on 2017. Thanks!
