### ISSUE TITLE
change text on http://torontojazz.com/tdj-news

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2016#34]
Hi Andrew - please update the text at http://torontojazz.com/tdj-news to read:

The TDJ News Corps is an annual initiative geared towards post-secondary students who are interested in writing about jazz. Successful applicants to the TDJ News Corps program are given full media accreditation for the TD Toronto Jazz Festival, granting them unprecedented access to the festival – attending and reviewing concerts for free, interviewing artists and experiencing the festival from behind the scenes. In addition, TDJ News Corps members are assigned a mentor – an experienced music journalist. 

The 2016 TDJ News Corps was <a hfef="http://torontojazz.com/david-cruz-tdj-news-corps">David Cruz</a>, a music student at York University, and <a href="http://torontojazz.com/warren-schlote-tdj-news-corps">Warren Schlote</a>, a media studies student at University of Guelph-Humber; mentors were John Terauds, founder of musicaltoronto.org and former Toronto Star writer, and Mark Wigmore, Senior Arts Editor at JAZZ.FM91.

Details on the 2017 TDJ News Corps will be announced soon.  Check this page throughout the Festival for TDJ News Corps articles – concert reviews, artist interviews and other editorial content.

**Comment by andrewfn** [comment]
moved to 2017 issues: https://github.com/jazzto/2017/issues/12
