### ISSUE TITLE
April Festival announcement

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2016#5]
Can you give me some advance warning of when your 2016 public festival announcement is going to be so I can make sure I'm ok for that day?

**Comment by andrewfn** [comment]
Sounds like this will be April 12.
Do you want it going live at a specific time in the day, or just at midnight the day before. (So I can plan my activities for the day.)

**Comment by andrewfn** [comment]
Brian, please let me know if and when you want me to refresh the test website to get the latest content.

**Comment by brianblain** [comment]
I've been refreshing cache after I make changes - is that doing the same thing.  Anyway, go ahead and refresh from your end.

**Comment by andrewfn** [comment]
I hope you have been making the changes to the actual website and not the test preview.
The test site is wiped every time I refresh it.

**Comment by brianblain** [comment]
*****I just saw that when I prioritized some shows that I did it on test site. Argh. But it looks like all the rest has been properly entered. There's some shows on the real site that aren't on the test site. Can you tell from your end if there's anything on test site that should be on the real site before you do the refresh?? B

**Comment by brianblain** [comment]
OK I've checked with everybody - please go ahead and refresh the test site

**Comment by andrewfn** [comment]
Test site refreshed

**Comment by andrewfn** [comment]
I'm ready to go live as soon as you give me the go-ahead. Do you know approximately when it will be?

**Comment by andrewfn** [comment]
In previous years we have had 15 or 18 shows on the home page running up to the festival. (At one point last year there were 24). Right now there are only 12. I can enable some more rows if you have them ready.
