### ISSUE TITLE
navigating the back end

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2016#8]
Hi - is there a way to search for a particular page on the back end?  For example - if I want to find a past concert page, which is now unpublished, is there a way to search?  Or it going through the pages alphabetically the only way?

**Comment by andrewfn** [comment]
I did some research on this and it looks like I have to make you a search interface.
This is not too difficult.
- What kind of content are you searching for? I assume it is concerts or artists?
- I assume that searching words contained in the titles would suffice. Is that correct?

**Comment by joshgrossman** [comment]
Yes - I'd be searching for concerts and artists.  And most likely concerts, since artist pages are rarely unpublished. And yes - searching title keywords should suffice.

Thanks.

**Comment by andrewfn** [comment]
I have built an artist search page here: http://torontojazz.com/artist-search
I would guess that @brianblain and the rest of the team would find it useful as well.
- Let me know if that is what you need
- For the concert search it might be a little trickier, depending on how long ago the concert was. (Future and recent concerts are easily found from the artist search.) Can you give me a little more info about what criteria you would use to find a concert apart from the artist name?

**Comment by andrewfn** [comment]
I have built a concert search page here: http://torontojazz.com/concert-search
- I did a bit of testing and it seems to be working ok, but I'm doing some more testing to make sure.
- Let me know how it is working for you.

**Comment by joshgrossman** [comment]
Thanks Andrew - that looks great and will save a lot of time!

**Comment by andrewfn** [comment]
Great!
