### ISSUE TITLE
test site

### ISSUE THREAD

**Issue by brianblain** [jazzto/2016#9]
Andrew can you set up test.jazz.to so we can see how to prioritize artists on the front page and start to test & proof.  We go live april 12

**Comment by andrewfn** [comment]
Ok, will do!

**Comment by andrewfn** [comment]
I've set up http://test.torontojazz.com/
Let me know if anything more needs doing on it.

**Comment by brianblain** [comment]
xcellent! Thanks, B

On Sun, Apr 3, 2016 at 11:45 PM, Andrew Fountain notifications@github.com
wrote:

> I've set up http://test.torontojazz.com/
> Let me know if anything more needs doing on it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2016/issues/9#issuecomment-205122438

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival  June 23 - July 3, 2016
30th Anniversary
